<?php

use Illuminate\Database\Seeder;

class PakistanDistrictTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('pakistan_districts')->truncate();

        \DB::table('pakistan_districts')->insert(array(

            /**
             *
             * Balochistan Districts Start here
             *
             */
            0 =>
                array(
                    'id' => 1,
                    'province_id' => 1,
                    'division_id' => 1,
                    'name' => 'Awaran',
                    'center' => null,
                    'population' => 122011,
                    'area' => 24945,
                    'density' => 4.891,
                    'latitude' => 26.4230985,
                    'longitude' => 64.0712359,
                    'map_zoom' => 8,
                ),
            1 =>
                array(
                    'id' => 2,
                    'province_id' => 1,
                    'division_id' => 6,
                    'name' => 'Barkhan',
                    'center' => null,
                    'population' => 171556,
                    'area' => 3494,
                    'density' => 49.10,
                    'latitude' => 29.8985847,
                    'longitude' => 69.5169987,
                    'map_zoom' => 8,
                ),
            2 =>
                array(
                    'id' => 3,
                    'province_id' => 1,
                    'division_id' => 7,
                    'name' => 'Chagai',
                    'center' => null,
                    'population' => 226008,
                    'area' => 44411,
                    'density' => 5.089,
                    'latitude' => 28.8727585,
                    'longitude' => 62.0550692,
                    'map_zoom' => 8,
                ),
            3 =>
                array(
                    'id' => 4,
                    'province_id' => 1,
                    'division_id' => 5,
                    'name' => 'Dera Bugti',
                    'center' => null,
                    'population' => 312603,
                    'area' => 10270,
                    'density' => 30.44,
                    'latitude' => 29.0589523,
                    'longitude' => 68.4586892,
                    'map_zoom' => 9,
                ),
            4 =>
                array(
                    'id' => 5,
                    'province_id' => 1,
                    'division_id' => 2,
                    'name' => 'Gwadar',
                    'center' => null,
                    'population' => 263514,
                    'area' => 11412,
                    'density' => 23.09,
                    'latitude' => 25.4000165,
                    'longitude' => 62.3069065,
                    'map_zoom' => 8,
                ),
            5 =>
                array(
                    'id' => 6,
                    'province_id' => 1,
                    'division_id' => 5,
                    'name' => 'Harnai',
                    'center' => null,
                    'population' => 97017,
                    'area' => 3052,
                    'density' => 31.79,
                    'latitude' => 30.0374376,
                    'longitude' => 67.2568493,
                    'map_zoom' => 9,
                ),
            6 =>
                array(
                    'id' => 7,
                    'province_id' => 1,
                    'division_id' => 3,
                    'name' => 'Jaffarabad',
                    'center' => null,
                    'population' => 513813,
                    'area' => 1796,
                    'density' => 286.1,
                    'latitude' => 28.3065236,
                    'longitude' => 67.8182817,
                    'map_zoom' => 9,
                ),
            7 =>
                array(
                    'id' => 8,
                    'province_id' => 1,
                    'division_id' => 3,
                    'name' => 'Jhal Magsi',
                    'center' => null,
                    'population' => 149225,
                    'area' => 3841,
                    'density' => 38.85,
                    'latitude' => 28.3742444,
                    'longitude' => 66.9200534,
                    'map_zoom' => 9,
                ),
            8 =>
                array(
                    'id' => 9,
                    'province_id' => 1,
                    'division_id' => 3,
                    'name' => 'Kachhi (Bolan)',
                    'center' => null,
                    'population' => 237030,
                    'area' => 5330,
                    'density' => 44.47,
                    'latitude' => 29.3649174,
                    'longitude' => 67.2542233,
                    'map_zoom' => 9,
                ),
            9 =>
                array(
                    'id' => 10,
                    'province_id' => 1,
                    'division_id' => 1,
                    'name' => 'Kalat',
                    'center' => null,
                    'population' => 412232,
                    'area' => 13851,
                    'density' => 29.76,
                    'latitude' => 28.7779145,
                    'longitude' => 65.5245694,
                    'map_zoom' => 8,
                ),
            10 =>
                array(
                    'id' => 11,
                    'province_id' => 1,
                    'division_id' => 2,
                    'name' => 'Kech',
                    'center' => null,
                    'population' => 909116,
                    'area' => 24083,
                    'density' => 37.75,
                    'latitude' => 26.0054021,
                    'longitude' => 61.9828762,
                    'map_zoom' => 8,
                ),
            11 =>
                array(
                    'id' => 12,
                    'province_id' => 1,
                    'division_id' => 7,
                    'name' => 'Kharan',
                    'center' => null,
                    'population' => 156152,
                    'area' => 10705,
                    'density' => 14.59,
                    'latitude' => 28.6791513,
                    'longitude' => 64.8872206,
                    'map_zoom' => 9,
                ),
            12 =>
                array(
                    'id' => 13,
                    'province_id' => 1,
                    'division_id' => 1,
                    'name' => 'Khuzdar',
                    'center' => null,
                    'population' => 802207,
                    'area' => 30983,
                    'density' => 25.89,
                    'latitude' => 27.2840995,
                    'longitude' => 64.2552182,
                    'map_zoom' => 7,
                ),
            13 =>
                array(
                    'id' => 14,
                    'province_id' => 1,
                    'division_id' => 4,
                    'name' => 'Killa Abdullah',
                    'center' => null,
                    'population' => 757578,
                    'area' => 5768,
                    'density' => 131.3,
                    'latitude' => 30.6857934,
                    'longitude' => 66.206849,
                    'map_zoom' => 9,
                ),
            14 =>
                array(
                    'id' => 15,
                    'province_id' => 1,
                    'division_id' => 6,
                    'name' => 'Killa Saifullah',
                    'center' => null,
                    'population' => 342814,
                    'area' => 12409,
                    'density' => 27.63,
                    'latitude' => 31.0521146,
                    'longitude' => 67.8454379,
                    'map_zoom' => 9,
                ),
            15 =>
                array(
                    'id' => 16,
                    'province_id' => 1,
                    'division_id' => 5,
                    'name' => 'Kohlu',
                    'center' => null,
                    'population' => 214350,
                    'area' => 7690,
                    'density' => 27.87,
                    'latitude' => 29.6459004,
                    'longitude' => 68.3163559,
                    'map_zoom' => 9,
                ),
            16 =>
                array(
                    'id' => 17,
                    'province_id' => 1,
                    'division_id' => 1,
                    'name' => 'Lasbela',
                    'center' => null,
                    'population' => 574292,
                    'area' => 14115,
                    'density' => 40.69,
                    'latitude' => 25.772088,
                    'longitude' => 65.1967902,
                    'map_zoom' => 8,
                ),
            17 =>
                array(
                    'id' => 18,
                    'province_id' => 1,
                    'division_id' => 5,
                    'name' => 'Lehri',
                    'center' => null,
                    'population' => 118046,
                    'area' => 3285,
                    'density' => 35.93,
                    'latitude' => 29.0770779,
                    'longitude' => 67.9223296,
                    'map_zoom' => 8,
                ),
            18 =>
                array(
                    'id' => 19,
                    'province_id' => 1,
                    'division_id' => 6,
                    'name' => 'Loralai',
                    'center' => null,
                    'population' => 397400,
                    'area' => 8143,
                    'density' => 48.80,
                    'latitude' => 30.2975298,
                    'longitude' => 68.1574096,
                    'map_zoom' => 9,
                ),
            19 =>
                array(
                    'id' => 20,
                    'province_id' => 1,
                    'division_id' => 1,
                    'name' => 'Mastung',
                    'center' => null,
                    'population' => 266461,
                    'area' => 5703,
                    'density' => 46.72,
                    'latitude' => 29.7946059,
                    'longitude' => 66.2558272,
                    'map_zoom' => 9,
                ),
            20 =>
                array(
                    'id' => 21,
                    'province_id' => 1,
                    'division_id' => 6,
                    'name' => 'Musakhel',
                    'center' => null,
                    'population' => 167017,
                    'area' => 5979,
                    'density' => 27.93,
                    'latitude' => 30.8973311,
                    'longitude' => 69.320389,
                    'map_zoom' => 9,
                ),
            21 =>
                array(
                    'id' => 22,
                    'province_id' => 1,
                    'division_id' => 3,
                    'name' => 'Nasirabad',
                    'center' => null,
                    'population' => 490538,
                    'area' => 3230,
                    'density' => 151.9,
                    'latitude' => 26.0693868,
                    'longitude' => 62.6978372,
                    'map_zoom' => 9,
                ),
            22 =>
                array(
                    'id' => 23,
                    'province_id' => 1,
                    'division_id' => 7,
                    'name' => 'Nushki',
                    'center' => null,
                    'population' => 178796,
                    'area' => 5826,
                    'density' => 30.69,
                    'latitude' => 29.4479131,
                    'longitude' => 65.1614969,
                    'map_zoom' => 9,
                ),
            23 =>
                array(
                    'id' => 24,
                    'province_id' => 1,
                    'division_id' => 2,
                    'name' => 'Panjgur',
                    'center' => null,
                    'population' => 316385,
                    'area' => 17577,
                    'density' => 18.00,
                    'latitude' => 26.7246367,
                    'longitude' => 63.6450804,
                    'map_zoom' => 9,
                ),
            24 =>
                array(
                    'id' => 25,
                    'province_id' => 1,
                    'division_id' => 4,
                    'name' => 'Pishin',
                    'center' => null,
                    'population' => 736481,
                    'area' => 4929,
                    'density' => 149.4,
                    'latitude' => 30.8027469,
                    'longitude' => 66.7357118,
                    'map_zoom' => 9,
                ),
            25 =>
                array(
                    'id' => 26,
                    'province_id' => 1,
                    'division_id' => 4,
                    'name' => 'Quetta',
                    'center' => null,
                    'population' => 2275699,
                    'area' => 2741,
                    'density' => 830.3,
                    'latitude' => 30.1837994,
                    'longitude' => 66.8225671,
                    'map_zoom' => 10,
                ),
            26 =>
                array(
                    'id' => 27,
                    'province_id' => 1,
                    'division_id' => 6,
                    'name' => 'Sheerani (Sherani)',
                    'center' => null,
                    'population' => 153116,
                    'area' => 2948,
                    'density' => 51.93,
                    'latitude' => 31.687966,
                    'longitude' => 69.2351799,
                    'map_zoom' => 9,
                ),
            27 =>
                array(
                    'id' => 28,
                    'province_id' => 1,
                    'division_id' => 5,
                    'name' => 'Sibi',
                    'center' => null,
                    'population' => 135572,
                    'area' => 4953,
                    'density' => 27.37,
                    'latitude' => 29.449775,
                    'longitude' => 67.4064194,
                    'map_zoom' => 9,
                ),
            28 =>
                array(
                    'id' => 29,
                    'province_id' => 1,
                    'division_id' => 3,
                    'name' => 'Sohbatpur',
                    'center' => null,
                    'population' => 200538,
                    'area' => 1412,
                    'density' => 142.0,
                    'latitude' => 28.5542015,
                    'longitude' => 68.4748587,
                    'map_zoom' => 9,
                ),
            29 =>
                array(
                    'id' => 30,
                    'province_id' => 1,
                    'division_id' => 7,
                    'name' => 'Washuk',
                    'center' => null,
                    'population' => 176206,
                    'area' => 36527,
                    'density' => 4.824,
                    'latitude' => 27.7797803,
                    'longitude' => 63.2582022,
                    'map_zoom' => 8,
                ),
            30 =>
                array(
                    'id' => 31,
                    'province_id' => 1,
                    'division_id' => 6,
                    'name' => 'Zhob',
                    'center' => null,
                    'population' => 310544,
                    'area' => 11931,
                    'density' => 26.03,
                    'latitude' => 31.2206996,
                    'longitude' => 67.6570194,
                    'map_zoom' => 8,
                ),
            31 =>
                array(
                    'id' => 32,
                    'province_id' => 1,
                    'division_id' => 5,
                    'name' => 'Ziarat',
                    'center' => null,
                    'population' => 160422,
                    'area' => 3266,
                    'density' => 49.13,
                    'latitude' => 30.3769281,
                    'longitude' => 67.3233459,
                    'map_zoom' => 9,
                ),

            /**
             *
             * FATA Start here
             *
             */
            32 =>
                array(
                    'id' => 33,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Bajaur',
                    'center' => null,
                    'population' => 1093684,
                    'area' => 1359,
                    'density' => 804.7,
                    'latitude' => 34.7438267,
                    'longitude' => 71.2086009,
                    'map_zoom' => 10,
                ),
            39 =>
                array(
                    'id' => 34,
                    'province_id' => 3,
                    'division_id' => 14,
                    'name' => 'Khyber',
                    'center' => null,
                    'population' => 986973,
                    'area' => 2743,
                    'density' => 359.8,
                    'latitude' => 34.0397121,
                    'longitude' => 70.6998726,
                    'map_zoom' => 10,
                ),
            40 =>
                array(
                    'id' => 35,
                    'province_id' => 3,
                    'division_id' => 11,
                    'name' => 'Kurram',
                    'center' => null,
                    'population' => 619553,
                    'area' => 3389,
                    'density' => 182.8,
                    'latitude' => 33.6898032,
                    'longitude' => 69.746923,
                    'map_zoom' => 9,
                ),
            41 =>
                array(
                    'id' => 36,
                    'province_id' => 3,
                    'division_id' => 14,
                    'name' => 'Mohmand',
                    'center' => null,
                    'population' => 466984,
                    'area' => 2258,
                    'density' => 206.8,
                    'latitude' => 34.4461992,
                    'longitude' => 71.0686006,
                    'map_zoom' => 10,
                ),
            42 =>
                array(
                    'id' => 37,
                    'province_id' => 3,
                    'division_id' => 8,
                    'name' => 'North Waziristan',
                    'center' => null,
                    'population' => 543254,
                    'area' => 4894,
                    'density' => 111.0,
                    'latitude' => 32.9567307,
                    'longitude' => 69.4496753,
                    'map_zoom' => 9,
                ),
            43 =>
                array(
                    'id' => 38,
                    'province_id' => 3,
                    'division_id' => 11,
                    'name' => 'Orakzai',
                    'center' => null,
                    'population' => 254356,
                    'area' => 1376,
                    'density' => 184.9,
                    'latitude' => 33.6957615,
                    'longitude' => 70.7184208,
                    'map_zoom' => 10,
                ),

            44 =>
                array(
                    'id' => 39,
                    'province_id' => 3,
                    'division_id' => 9,
                    'name' => 'South Waziristan',
                    'center' => null,
                    'population' => 674065,
                    'area' => 6231,
                    'density' => 108.2,
                    'latitude' => 32.29156,
                    'longitude' => 69.2502877,
                    'map_zoom' => 9,
                ),

            /**
             *
             * Islamabad Start here
             *
             */
            45 =>
                array(
                    'id' => 40,
                    'province_id' => 2,
                    'division_id' => 0,
                    'name' => 'Islamabad',
                    'center' => 'Islamabad',
                    'population' => 2001579,
                    'area' => 906,
                    'density' => 2, 210,
                    'latitude' => 33.6209086,
                    'longitude' => 72.8060347,
                    'map_zoom' => 10,
                ),

            /**
             *
             * KPK Start here
             *
             */

            46 =>
                array(
                    'id' => 41,
                    'province_id' => 3,
                    'division_id' => 10,
                    'name' => 'Abbottabad',
                    'center' => 'Abbottabad',
                    'population' => 1332912,
                    'area' => 1756,
                    'density' => 759.1,
                    'latitude' => 34.0943949,
                    'longitude' => 72.9664607,
                    'map_zoom' => 10,
                ),

            47 =>
                array(
                    'id' => 42,
                    'province_id' => 3,
                    'division_id' => 8,
                    'name' => 'Bannu',
                    'center' => null,
                    'population' => 1167892,
                    'area' => 1183,
                    'density' => 987.6,
                    'latitude' => 32.8992214,
                    'longitude' => 70.3845205,
                    'map_zoom' => 10,
                ),
            48 =>
                array(
                    'id' => 43,
                    'province_id' => 3,
                    'division_id' => 10,
                    'name' => 'Batagram',
                    'center' => null,
                    'population' => 476612,
                    'area' => 1356,
                    'density' => 351.6,
                    'latitude' => 34.7621113,
                    'longitude' => 72.8990863,
                    'map_zoom' => 10,
                ),
            49 =>
                array(
                    'id' => 44,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Buner',
                    'center' => null,
                    'population' => 897319,
                    'area' => 1735,
                    'density' => 517.2,
                    'latitude' => 34.4325154,
                    'longitude' => 72.2056874,
                    'map_zoom' => 10,
                ),
            50 =>
                array(
                    'id' => 45,
                    'province_id' => 3,
                    'division_id' => 14,
                    'name' => 'Charsadda',
                    'center' => null,
                    'population' => 1616198,
                    'area' => 991,
                    'density' => 1630,
                    'latitude' => 34.2528865,
                    'longitude' => 71.4233189,
                    'map_zoom' => 10,
                ),
            51 =>
                array(
                    'id' => 46,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Chitral',
                    'center' => null,
                    'population' => 447362,
                    'area' => 14755,
                    'density' => 30.32,
                    'latitude' => 36.0613873,
                    'longitude' => 71.4122308,
                    'map_zoom' => 8,
                ),
            52 =>
                array(
                    'id' => 47,
                    'province_id' => 3,
                    'division_id' => 9,
                    'name' => 'Dera Ismail Khan',
                    'center' => null,
                    'population' => 1627132,
                    'area' => 7381,
                    'density' => 220.4,
                    'latitude' => 31.8881192,
                    'longitude' => 70.1987817,
                    'map_zoom' => 9,
                ),
            53 =>
                array(
                    'id' => 48,
                    'province_id' => 3,
                    'division_id' => 11,
                    'name' => 'Hangu',
                    'center' => null,
                    'population' => 518798,
                    'area' => 1380,
                    'density' => 375.9,
                    'latitude' => 33.4110782,
                    'longitude' => 70.5821937,
                    'map_zoom' => 10,
                ),
            54 =>
                array(
                    'id' => 49,
                    'province_id' => 3,
                    'division_id' => 10,
                    'name' => 'Haripur',
                    'center' => null,
                    'population' => 1003031,
                    'area' => 1927,
                    'density' => 5205,
                    'latitude' => 34.0481174,
                    'longitude' => 72.6034633,
                    'map_zoom' => 10,
                ),
            55 =>
                array(
                    'id' => 50,
                    'province_id' => 3,
                    'division_id' => 11,
                    'name' => 'Karak',
                    'center' => null,
                    'population' => 706299,
                    'area' => 2653,
                    'density' => 266.2,
                    'latitude' => 33.090729,
                    'longitude' => 70.837292,
                    'map_zoom' => 10,
                ),
            56 =>
                array(
                    'id' => 51,
                    'province_id' => 3,
                    'division_id' => 11,
                    'name' => 'Kohat',
                    'center' => null,
                    'population' => 993874,
                    'area' => 2975,
                    'density' => 334.0,
                    'latitude' => 33.4012109,
                    'longitude' => 70.9782703,
                    'map_zoom' => 9,
                ),
            57 =>
                array(
                    'id' => 52,
                    'province_id' => 3,
                    'division_id' => 10,
                    'name' => 'Kohistan (Lower Kohistan - Upper Kohistan)',
                    'center' => null,
                    'population' => 784711,
                    'area' => 7655,
                    'density' => 102.5,
                    'latitude' => 35.3875867,
                    'longitude' => 72.8159773,
                    'map_zoom' => 9,
                ),
            58 =>
                array(
                    'id' => 53,
                    'province_id' => 3,
                    'division_id' => 8,
                    'name' => 'Lakki Marwat',
                    'center' => null,
                    'population' => 876182,
                    'area' => 3185,
                    'density' => 275.1,
                    'latitude' => 32.569847,
                    'longitude' => 70.5429401,
                    'map_zoom' => 10,
                ),
            59 =>
                array(
                    'id' => 54,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Lower Dir',
                    'center' => null,
                    'population' => 1435917,
                    'area' => 1758,
                    'density' => 816.8,
                    'latitude' => 34.8494307,
                    'longitude' => 71.5709686,
                    'map_zoom' => 10,
                ),
            60 =>
                array(
                    'id' => 55,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Malakand',
                    'center' => null,
                    'population' => 720295,
                    'area' => 948,
                    'density' => 760,
                    'latitude' => 34.5143657,
                    'longitude' => 71.6586652,
                    'map_zoom' => 10,
                ),
            61 =>
                array(
                    'id' => 56,
                    'province_id' => 3,
                    'division_id' => 10,
                    'name' => 'Mansehra',
                    'center' => null,
                    'population' => 1556460,
                    'area' => 4287,
                    'density' => 363.1,
                    'latitude' => 34.6992218,
                    'longitude' => 72.914039,
                    'map_zoom' => 9,
                ),
            62 =>
                array(
                    'id' => 57,
                    'province_id' => 3,
                    'division_id' => 13,
                    'name' => 'Mardan',
                    'center' => null,
                    'population' => 2373061,
                    'area' => 1639,
                    'density' => 1448,
                    'latitude' => 34.3044468,
                    'longitude' => 71.8457576,
                    'map_zoom' => 10,
                ),
            63 =>
                array(
                    'id' => 58,
                    'province_id' => 3,
                    'division_id' => 14,
                    'name' => 'Nowshera',
                    'center' => null,
                    'population' => 1518540,
                    'area' => 1, 746,
                    'density' => 869.8,
                    'latitude' => 33.9175777,
                    'longitude' => 71.6930951,
                    'map_zoom' => 10,
                ),
            64 =>
                array(
                    'id' => 59,
                    'province_id' => 3,
                    'division_id' => 14,
                    'name' => 'Peshawar',
                    'center' => null,
                    'population' => 4269079,
                    'area' => 1257,
                    'density' => 3395,
                    'latitude' => 33.970333,
                    'longitude' => 71.294073,
                    'map_zoom' => 10,
                ),
            65 =>
                array(
                    'id' => 60,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Shangla',
                    'center' => null,
                    'population' => 757810,
                    'area' => 1389,
                    'density' => 545.7,
                    'latitude' => 34.84586,
                    'longitude' => 72.4856318,
                    'map_zoom' => 10,
                ),
            66 =>
                array(
                    'id' => 61,
                    'province_id' => 3,
                    'division_id' => 13,
                    'name' => 'Swabi',
                    'center' => null,
                    'population' => 1624616,
                    'area' => 1481,
                    'density' => 1097,
                    'latitude' => 34.1405397,
                    'longitude' => 72.2082851,
                    'map_zoom' => 10,
                ),
            67 =>
                array(
                    'id' => 62,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Swat',
                    'center' => null,
                    'population' => 2309570,
                    'area' => 5367,
                    'density' => 430.4,
                    'latitude' => 35.2330373,
                    'longitude' => 71.3244717,
                    'map_zoom' => 8,
                ),
            68 =>
                array(
                    'id' => 63,
                    'province_id' => 3,
                    'division_id' => 9,
                    'name' => 'Tank',
                    'center' => null,
                    'population' => 391885,
                    'area' => 1675,
                    'density' => 234,
                    'latitude' => 32.2531685,
                    'longitude' => 70.1090653,
                    'map_zoom' => 10,
                ),
            69 =>
                array(
                    'id' => 64,
                    'province_id' => 3,
                    'division_id' => 10,
                    'name' => 'Tor Ghar (Kala Dhaka)',
                    'center' => null,
                    'population' => 171395,
                    'area' => 467,
                    'density' => 366.9,
                    'latitude' => 34.5473571,
                    'longitude' => 72.548452,
                    'map_zoom' => 10,
                ),
            70 =>
                array(
                    'id' => 65,
                    'province_id' => 3,
                    'division_id' => 12,
                    'name' => 'Upper Dir',
                    'center' => null,
                    'population' => 946421,
                    'area' => 3586,
                    'density' => 263.9,
                    'latitude' => 35.3084004,
                    'longitude' => 71.3903651,
                    'map_zoom' => 9,
                ),


            /**
             *
             * Punjab Start here
             *
             */
            71 =>
                array(
                    'id' => 66,
                    'province_id' => 4,
                    'division_id' => 21,
                    'name' => 'Attock',
                    'center' => null,
                    'population' => 1883556,
                    'area' => 6827,
                    'density' => 275.9,
                    'latitude' => 33.5954533,
                    'longitude' => 71.9872338,
                    'map_zoom' => 10,
                ),
            72 =>
                array(
                    'id' => 67,
                    'province_id' => 4,
                    'division_id' => 15,
                    'name' => 'Bahawalnagar',
                    'center' => null,
                    'population' => 2981919,
                    'area' => 8551,
                    'density' => 348.7,
                    'latitude' => 29.979276,
                    'longitude' => 73.0876223,
                    'map_zoom' => 10,
                ),
            73 =>
                array(
                    'id' => 68,
                    'province_id' => 4,
                    'division_id' => 15,
                    'name' => 'Bahawalpur',
                    'center' => null,
                    'population' => 3668106,
                    'area' => 23910,
                    'density' => 153.4,
                    'latitude' => 28.8247672,
                    'longitude' => 70.7123739,
                    'map_zoom' => 8,
                ),
            74 =>
                array(
                    'id' => 69,
                    'province_id' => 4,
                    'division_id' => 23,
                    'name' => 'Bhakkar',
                    'center' => null,
                    'population' => 1650518,
                    'area' => 8, 522,
                    'density' => 193.7,
                    'latitude' => 31.671212,
                    'longitude' => 70.8544182,
                    'map_zoom' => 9,
                ),
            75 =>
                array(
                    'id' => 70,
                    'province_id' => 4,
                    'division_id' => 21,
                    'name' => 'Chakwal',
                    'center' => null,
                    'population' => 1495982,
                    'area' => 6680,
                    'density' => 223.9,
                    'latitude' => 32.8810207,
                    'longitude' => 71.9551755,
                    'map_zoom' => 9,
                ),
            76 =>
                array(
                    'id' => 71,
                    'province_id' => 4,
                    'division_id' => 17,
                    'name' => 'Chiniot',
                    'center' => null,
                    'population' => 1369740,
                    'area' => 2610,
                    'density' => 524.9,
                    'latitude' => 31.6695023,
                    'longitude' => 72.5527042,
                    'map_zoom' => 10,
                ),
            77 =>
                array(
                    'id' => 72,
                    'province_id' => 4,
                    'division_id' => 16,
                    'name' => 'Dera Ghazi Khan',
                    'center' => null,
                    'population' => 2872201,
                    'area' => 11690,
                    'density' => 245.7,
                    'latitude' => 30.0174444,
                    'longitude' => 70.1337421,
                    'map_zoom' => 9,
                ),
            78 =>
                array(
                    'id' => 73,
                    'province_id' => 4,
                    'division_id' => 17,
                    'name' => 'Faisalabad',
                    'center' => null,
                    'population' => 7874790,
                    'area' => 5960,
                    'density' => 1321,
                    'latitude' => 31.4237883,
                    'longitude' => 72.9492131,
                    'map_zoom' => 11,
                ),
            79 =>
                array(
                    'id' => 74,
                    'province_id' => 4,
                    'division_id' => 18,
                    'name' => 'Gujranwala',
                    'center' => null,
                    'population' => 5, 014, 196,
                    'area' => 3624,
                    'density' => 1384,
                    'latitude' => 32.1850868,
                    'longitude' => 73.5706598,
                    'map_zoom' => 9,
                ),
            80 =>
                array(
                    'id' => 75,
                    'province_id' => 4,
                    'division_id' => 18,
                    'name' => 'Gujrat',
                    'center' => null,
                    'population' => 2756110,
                    'area' => 3177,
                    'density' => 867.7,
                    'latitude' => 32.7186682,
                    'longitude' => 73.746858,
                    'map_zoom' => 10,
                ),
            81 =>
                array(
                    'id' => 76,
                    'province_id' => 4,
                    'division_id' => 18,
                    'name' => 'Hafizabad',
                    'center' => null,
                    'population' => 1156957,
                    'area' => 2274,
                    'density' => 508.9,
                    'latitude' => 32.0750159,
                    'longitude' => 73.6501922,
                    'map_zoom' => 11,
                ),
            82 =>
                array(
                    'id' => 77,
                    'province_id' => 4,
                    'division_id' => 17,
                    'name' => 'Jhang',
                    'center' => null,
                    'population' => 2744085,
                    'area' => 6353,
                    'density' => 431.9,
                    'latitude' => 31.1690747,
                    'longitude' => 71.6840042,
                    'map_zoom' => 9,
                ),
            83 =>
                array(
                    'id' => 78,
                    'province_id' => 4,
                    'division_id' => 21,
                    'name' => 'Jhelum',
                    'center' => null,
                    'population' => 1222650,
                    'area' => 3579,
                    'density' => 341.6,
                    'latitude' => 32.9275559,
                    'longitude' => 73.6310257,
                    'map_zoom' => 11,
                ),
            84 =>
                array(
                    'id' => 79,
                    'province_id' => 4,
                    'division_id' => 19,
                    'name' => 'Kasur',
                    'center' => null,
                    'population' => 3454996,
                    'area' => 3894,
                    'density' => 887.2,
                    'latitude' => 31.0054989,
                    'longitude' => 73.6133805,
                    'map_zoom' => 11,
                ),
            85 =>
                array(
                    'id' => 80,
                    'province_id' => 4,
                    'division_id' => 20,
                    'name' => 'Khanewal',
                    'center' => null,
                    'population' => 2921986,
                    'area' => 4362,
                    'density' => 669.8,
                    'latitude' => 30.3154422,
                    'longitude' => 71.4716208,
                    'map_zoom' => 9,
                ),
            86 =>
                array(
                    'id' => 81,
                    'province_id' => 4,
                    'division_id' => 23,
                    'name' => 'Khushab',
                    'center' => null,
                    'population' => 1281299,
                    'area' => 6622,
                    'density' => 193.5,
                    'latitude' => 32.121568,
                    'longitude' => 71.5841065,
                    'map_zoom' => 9,
                ),
            87 =>
                array(
                    'id' => 82,
                    'province_id' => 4,
                    'division_id' => 19,
                    'name' => 'Lahore',
                    'center' => null,
                    'population' => 11126285,
                    'area' => 1684,
                    'density' => 6606,
                    'latitude' => 31.498258,
                    'longitude' => 74.0437812,
                    'map_zoom' => 10,
                ),
            88 =>
                array(
                    'id' => 83,
                    'province_id' => 4,
                    'division_id' => 16,
                    'name' => 'Layyah',
                    'center' => null,
                    'population' => 1824230,
                    'area' => 6379,
                    'density' => 286.0,
                    'latitude' => 30.9847892,
                    'longitude' => 70.7371782,
                    'map_zoom' => 9,
                ),
            89 =>
                array(
                    'id' => 84,
                    'province_id' => 4,
                    'division_id' => 20,
                    'name' => 'Lodhran',
                    'center' => null,
                    'population' => 1700620,
                    'area' => 2662,
                    'density' => 638.9,
                    'latitude' => 29.6713605,
                    'longitude' => 71.4530413,
                    'map_zoom' => 10,
                ),
            90 =>
                array(
                    'id' => 85,
                    'province_id' => 4,
                    'division_id' => 18,
                    'name' => 'Mandi Bahauddin',
                    'center' => null,
                    'population' => 1593292,
                    'area' => 2759,
                    'density' => 577.5,
                    'latitude' => 32.4340673,
                    'longitude' => 73.191934,
                    'map_zoom' => 10,
                ),
            91 =>
                array(
                    'id' => 86,
                    'province_id' => 4,
                    'division_id' => 23,
                    'name' => 'Mianwali',
                    'center' => null,
                    'population' => 1546094,
                    'area' => 6029,
                    'density' => 256.4,
                    'latitude' => 32.7034859,
                    'longitude' => 70.9795894,
                    'map_zoom' => 9,
                ),
            92 =>
                array(
                    'id' => 87,
                    'province_id' => 4,
                    'division_id' => 20,
                    'name' => 'Multan',
                    'center' => null,
                    'population' => 4745109,
                    'area' => 3646,
                    'density' => 1302,
                    'latitude' => 29.9345784,
                    'longitude' => 70.8595855,
                    'map_zoom' => 9,
                ),
            93 =>
                array(
                    'id' => 88,
                    'province_id' => 4,
                    'division_id' => 16,
                    'name' => 'Muzaffargarh',
                    'center' => null,
                    'population' => 4325483,
                    'area' => 7668,
                    'density' => 564.1,
                    'latitude' => 29.8885682,
                    'longitude' => 70.0106365,
                    'map_zoom' => 8,
                ),
            94 =>
                array(
                    'id' => 89,
                    'province_id' => 4,
                    'division_id' => 19,
                    'name' => 'Nankana Sahib',
                    'center' => null,
                    'population' => 1356374,
                    'area' => 2774,
                    'density' => 489,
                    'latitude' => 31.4629503,
                    'longitude' => 73.1035713,
                    'map_zoom' => 9,
                ),
            95 =>
                array(
                    'id' => 90,
                    'province_id' => 4,
                    'division_id' => 18,
                    'name' => 'Narowal',
                    'center' => null,
                    'population' => 1709757,
                    'area' => 2324,
                    'density' => 735.8,
                    'latitude' => 32.2066667,
                    'longitude' => 74.7026309,
                    'map_zoom' => 10,
                ),
            96 =>
                array(
                    'id' => 91,
                    'province_id' => 4,
                    'division_id' => 22,
                    'name' => 'Okara',
                    'center' => null,
                    'population' => 3039139,
                    'area' => 4415,
                    'density' => 688.4,
                    'latitude' => 30.8013986,
                    'longitude' => 73.374257,
                    'map_zoom' => 11,
                ),
            97 =>
                array(
                    'id' => 92,
                    'province_id' => 4,
                    'division_id' => 22,
                    'name' => 'Pakpattan',
                    'center' => null,
                    'population' => 1823687,
                    'area' => 2889,
                    'density' => 631.4,
                    'latitude' => 30.2870921,
                    'longitude' => 72.9588734,
                    'map_zoom' => 10,
                ),
            98 =>
                array(
                    'id' => 93,
                    'province_id' => 4,
                    'division_id' => 15,
                    'name' => 'Rahim Yar Khan',
                    'center' => null,
                    'population' => 4814006,
                    'area' => 12885,
                    'density' => 373.6,
                    'latitude' => 28.4852682,
                    'longitude' => 69.1657641,
                    'map_zoom' => 8,
                ),
            99 =>
                array(
                    'id' => 94,
                    'province_id' => 4,
                    'division_id' => 16,
                    'name' => 'Rajanpur',
                    'center' => null,
                    'population' => 1995958,
                    'area' => 12530,
                    'density' => 159.3,
                    'latitude' => 29.1021006,
                    'longitude' => 70.3146866,
                    'map_zoom' => 10,
                ),
            100 =>
                array(
                    'id' => 95,
                    'province_id' => 4,
                    'division_id' => 21,
                    'name' => 'Rawalpindi',
                    'center' => null,
                    'population' => 5405633,
                    'area' => 5205,
                    'density' => 1039,
                    'latitude' => 33.5433244,
                    'longitude' => 72.5711916,
                    'map_zoom' => 9,
                ),
            101 =>
                array(
                    'id' => 96,
                    'province_id' => 4,
                    'division_id' => 22,
                    'name' => 'Sahiwal',
                    'center' => null,
                    'population' => 2517560,
                    'area' => 3224,
                    'density' => 781,
                    'latitude' => 30.5683753,
                    'longitude' => 72.317307,
                    'map_zoom' => 9,
                ),
            102 =>
                array(
                    'id' => 97,
                    'province_id' => 4,
                    'division_id' => 23,
                    'name' => 'Sargodha',
                    'center' => null,
                    'population' => 3703588,
                    'area' => 5780,
                    'density' => 640.7,
                    'latitude' => 32.0638825,
                    'longitude' => 72.2031223,
                    'map_zoom' => 9,
                ),
            103 =>
                array(
                    'id' => 98,
                    'province_id' => 4,
                    'division_id' => 19,
                    'name' => 'Sheikhupura',
                    'center' => null,
                    'population' => 3460426,
                    'area' => 3030,
                    'density' => 1142,
                    'latitude' => 31.7127966,
                    'longitude' => 73.6005826,
                    'map_zoom' => 9,
                ),
            104 =>
                array(
                    'id' => 99,
                    'province_id' => 4,
                    'division_id' => 18,
                    'name' => 'Sialkot',
                    'center' => null,
                    'population' => 3893672,
                    'area' => 3093,
                    'density' => 1259,
                    'latitude' => 32.4446941,
                    'longitude' => 74.013354,
                    'map_zoom' => 9,
                ),
            105 =>
                array(
                    'id' => 100,
                    'province_id' => 4,
                    'division_id' => 17,
                    'name' => 'Toba Tek Singh',
                    'center' => null,
                    'population' => 2190015,
                    'area' => 3073,
                    'density' => 712.8,
                    'latitude' => 30.9484063,
                    'longitude' => 71.9327864,
                    'map_zoom' => 9,
                ),
            106 =>
                array(
                    'id' => 101,
                    'province_id' => 4,
                    'division_id' => 20,
                    'name' => 'Vehari',
                    'center' => null,
                    'population' => 2897446,
                    'area' => 4486,
                    'density' => 645.9,
                    'latitude' => 29.9815045,
                    'longitude' => 71.8041439,
                    'map_zoom' => 9,
                ),


            /**
             *
             * Sindh Districts Start here
             *
             */
            107 =>
                array(
                    'id' => 102,
                    'province_id' => 5,
                    'division_id' => 24,
                    'name' => 'Badin',
                    'center' => null,
                    'population' => 1804516,
                    'area' => 6470,
                    'density' => 278.9,
                    'latitude' => 24.7517555,
                    'longitude' => 68.2826697,
                    'map_zoom' => 9,
                ),
            108 =>
                array(
                    'id' => 103,
                    'province_id' => 5,
                    'division_id' => 25,
                    'name' => 'Dadu',
                    'center' => null,
                    'population' => 1550266,
                    'area' => 8034,
                    'density' => 193,
                    'latitude' => 26.7578686,
                    'longitude' => 67.0032524,
                    'map_zoom' => 9,
                ),
            109 =>
                array(
                    'id' => 104,
                    'province_id' => 5,
                    'division_id' => 27,
                    'name' => 'Ghotki',
                    'center' => null,
                    'population' => 1647239,
                    'area' => 6506,
                    'density' => 253.2,
                    'latitude' => 27.8263814,
                    'longitude' => 69.1072531,
                    'map_zoom' => 9,
                ),
            110 =>
                array(
                    'id' => 105,
                    'province_id' => 5,
                    'division_id' => 25,
                    'name' => 'Hyderabad',
                    'center' => null,
                    'population' => 2201079,
                    'area' => 1022,
                    'density' => 2155,
                    'latitude' => 25.3565714,
                    'longitude' => 68.187067,
                    'map_zoom' => 10,
                ),
            111 =>
                array(
                    'id' => 106,
                    'province_id' => 5,
                    'division_id' => 28,
                    'name' => 'Jacobabad',
                    'center' => null,
                    'population' => 1006297,
                    'area' => 2771,
                    'density' => 363.1,
                    'latitude' => 28.2808819,
                    'longitude' => 68.4129052,
                    'map_zoom' => 11,
                ),
            112 =>
                array(
                    'id' => 107,
                    'province_id' => 5,
                    'division_id' => 25,
                    'name' => 'Jamshoro',
                    'center' => null,
                    'population' => 993142,
                    'area' => 11250,
                    'density' => 88.28,
                    'latitude' => 25.7850778,
                    'longitude' => 66.7454473,
                    'map_zoom' => 8,
                ),
            113 =>
                array(
                    'id' => 108,
                    'province_id' => 5,
                    'division_id' => 26,
                    'name' => 'Karachi Central',
                    'center' => null,
                    'population' => 2972639,
                    'area' => 61.5,
                    'density' => 48336,
                    'latitude' => 24.9443216,
                    'longitude' => 66.9784246,
                    'map_zoom' => 12,
                ),
            114 =>
                array(
                    'id' => 109,
                    'province_id' => 5,
                    'division_id' => 26,
                    'name' => 'Karachi East',
                    'center' => null,
                    'population' => 2909921,
                    'area' => 165,
                    'density' => 17625,
                    'latitude' => 24.87105,
                    'longitude' => 67.0466533,
                    'map_zoom' => 12,
                ),
            115 =>
                array(
                    'id' => 110,
                    'province_id' => 5,
                    'division_id' => 26,
                    'name' => 'Karachi South',
                    'center' => null,
                    'population' => 1791751,
                    'area' => 85,
                    'density' => 21079,
                    'latitude' => 24.819151,
                    'longitude' => 66.9586073,
                    'map_zoom' => 12,
                ),
            116 =>
                array(
                    'id' => 111,
                    'province_id' => 5,
                    'division_id' => 26,
                    'name' => 'Karachi West',
                    'center' => null,
                    'population' => 3914757,
                    'area' => 630,
                    'density' => 6212,
                    'latitude' => 25.0208454,
                    'longitude' => 66.6742761,
                    'map_zoom' => 10,
                ),
            117 =>
                array(
                    'id' => 112,
                    'province_id' => 5,
                    'division_id' => 28,
                    'name' => 'Kashmore',
                    'center' => null,
                    'population' => 1089169,
                    'area' => 2551,
                    'density' => 427,
                    'latitude' => 28.2535539,
                    'longitude' => 69.1506648,
                    'map_zoom' => 10,
                ),
            118 =>
                array(
                    'id' => 113,
                    'province_id' => 5,
                    'division_id' => 27,
                    'name' => 'Khairpur',
                    'center' => null,
                    'population' => 2405523,
                    'area' => 15925,
                    'density' => 151.1,
                    'latitude' => 26.9320816,
                    'longitude' => 68.0591974,
                    'map_zoom' => 8,
                ),
            119 =>
                array(
                    'id' => 114,
                    'province_id' => 5,
                    'division_id' => 26,
                    'name' => 'Korangi',
                    'center' => null,
                    'population' => 2457019,
                    'area' => 94.8,
                    'density' => 25918,
                    'latitude' => 24.8352945,
                    'longitude' => 67.0978735,
                    'map_zoom' => 13,
                ),
            120 =>
                array(
                    'id' => 115,
                    'province_id' => 5,
                    'division_id' => 28,
                    'name' => 'Larkana',
                    'center' => null,
                    'population' => 1524391,
                    'area' => 1906,
                    'density' => 799.7,
                    'latitude' => 27.5316293,
                    'longitude' => 67.6567237,
                    'map_zoom' => 9,
                ),
            121 =>
                array(
                    'id' => 116,
                    'province_id' => 5,
                    'division_id' => 26,
                    'name' => 'Malir',
                    'center' => null,
                    'population' => 2008901,
                    'area' => 2635,
                    'density' => 762.5,
                    'latitude' => 25.1998014,
                    'longitude' => 66.763812,
                    'map_zoom' => 9,
                ),
            122 =>
                array(
                    'id' => 117,
                    'province_id' => 5,
                    'division_id' => 25,
                    'name' => 'Matiari',
                    'center' => null,
                    'population' => 769349,
                    'area' => 1459,
                    'density' => 527.3,
                    'latitude' => 25.7669273,
                    'longitude' => 68.1720212,
                    'map_zoom' => 10,
                ),
            123 =>
                array(
                    'id' => 118,
                    'province_id' => 5,
                    'division_id' => 29,
                    'name' => 'Mirpur Khas',
                    'center' => null,
                    'population' => 1505876,
                    'area' => 3319,
                    'density' => 453.7,
                    'latitude' => 25.2776953,
                    'longitude' => 68.6220716,
                    'map_zoom' => 9,
                ),
            124 =>
                array(
                    'id' => 119,
                    'province_id' => 5,
                    'division_id' => 30,
                    'name' => 'Naushahro Feroze',
                    'center' => null,
                    'population' => 1612373,
                    'area' => 3027,
                    'density' => 532.6,
                    'latitude' => 26.89085,
                    'longitude' => 67.8446932,
                    'map_zoom' => 10,
                ),
            125 =>
                array(
                    'id' => 120,
                    'province_id' => 5,
                    'division_id' => 28,
                    'name' => 'Qambar Shahdadkot',
                    'center' => null,
                    'population' => 1341042,
                    'area' => 5599,
                    'density' => 239.5,
                    'latitude' => 27.646669,
                    'longitude' => 67.1239389,
                    'map_zoom' => 9,
                ),
            126 =>
                array(
                    'id' => 121,
                    'province_id' => 5,
                    'division_id' => 30,
                    'name' => 'Sanghar',
                    'center' => null,
                    'population' => 2057057,
                    'area' => 10259,
                    'density' => 200.5,
                    'latitude' => 25.9810303,
                    'longitude' => 68.7501505,
                    'map_zoom' => 9,
                ),
            127 =>
                array(
                    'id' => 122,
                    'province_id' => 5,
                    'division_id' => 30,
                    'name' => 'Shaheed Benazir Abad (Nawabshah)',
                    'center' => null,
                    'population' => 1612847,
                    'area' => 4618,
                    'density' => 349.2,
                    'latitude' => 26.3088502,
                    'longitude' => 68.083829,
                    'map_zoom' => 10,
                ),
            128 =>
                array(
                    'id' => 123,
                    'province_id' => 5,
                    'division_id' => 28,
                    'name' => 'Shikarpur',
                    'center' => null,
                    'population' => 1231481,
                    'area' => 2577,
                    'density' => 477.9,
                    'latitude' => 27.9265338,
                    'longitude' => 68.3699543,
                    'map_zoom' => 10,
                ),
            129 =>
                array(
                    'id' => 124,
                    'province_id' => 5,
                    'division_id' => 24,
                    'name' => 'Sujawal',
                    'center' => null,
                    'population' => 781967,
                    'area' => 8699,
                    'density' => 89.89,
                    'latitude' => 24.6036153,
                    'longitude' => 68.0606368,
                    'map_zoom' => 11,
                ),
            130 =>
                array(
                    'id' => 125,
                    'province_id' => 5,
                    'division_id' => 27,
                    'name' => 'Sukkur',
                    'center' => null,
                    'population' => 1487903,
                    'area' => 5216,
                    'density' => 285.3,
                    'latitude' => 27.5489361,
                    'longitude' => 68.6254691,
                    'map_zoom' => 9,
                ),
            131 =>
                array(
                    'id' => 126,
                    'province_id' => 5,
                    'division_id' => 25,
                    'name' => 'Tando Allahyar',
                    'center' => null,
                    'population' => 836887,
                    'area' => 1573,
                    'density' => 532.1,
                    'latitude' => 25.4811573,
                    'longitude' => 68.4902722,
                    'map_zoom' => 10,
                ),
            132 =>
                array(
                    'id' => 127,
                    'province_id' => 5,
                    'division_id' => 25,
                    'name' => 'Tando Muhammad Khan',
                    'center' => null,
                    'population' => 677228,
                    'area' => 1814,
                    'density' => 373.4,
                    'latitude' => 25.0238213,
                    'longitude' => 68.2268549,
                    'map_zoom' => 10,
                ),
            133 =>
                array(
                    'id' => 128,
                    'province_id' => 5,
                    'division_id' => 29,
                    'name' => 'Tharparkar',
                    'center' => null,
                    'population' => 1649661,
                    'area' => 19808,
                    'density' => 83.28,
                    'latitude' => 24.9414168,
                    'longitude' => 68.9688124,
                    'map_zoom' => 8,
                ),
            134 =>
                array(
                    'id' => 129,
                    'province_id' => 5,
                    'division_id' => 24,
                    'name' => 'Thatta',
                    'center' => null,
                    'population' => 979817,
                    'area' => 7705,
                    'density' => 127.2,
                    'latitude' => 24.6437493,
                    'longitude' => 67.3315641,
                    'map_zoom' => 8,
                ),
            135 =>
                array(
                    'id' => 130,
                    'province_id' => 5,
                    'division_id' => 29,
                    'name' => 'Umerkot',
                    'center' => null,
                    'population' => 1073146,
                    'area' => 5503,
                    'density' => 195,
                    'latitude' => 25.3386483,
                    'longitude' => 69.189482,
                    'map_zoom' => 9,
                ),


            /**
             *
             * Gilgit-Baltistan Districts Start here
             *
             */

            136 =>
                array(
                    'id' => 131,
                    'province_id' => 6,
                    'division_id' => 32,
                    'name' => 'Ghanche',
                    'center' => 'Khaplu',
                    'population' => 88366,
                    'area' => 6400,
                    'density' => null,
                    'latitude' => 35.1236275,
                    'longitude' => 76.0271902,
                    'map_zoom' => 9.7,
                ),
            137 =>
                array(
                    'id' => 132,
                    'province_id' => 6,
                    'division_id' => 32,
                    'name' => 'Skardu',
                    'center' => 'Skardu',
                    'population' => 214848,
                    'area' => 15000,
                    'density' => null,
                    'latitude' => 35.2623194,
                    'longitude' => 75.3119676,
                    'map_zoom' => 10,
                ),
            138 =>
                array(
                    'id' => 133,
                    'province_id' => 6,
                    'division_id' => 33,
                    'name' => 'Astore',
                    'center' => 'Gorikot',
                    'population' => 71666,
                    'area' => 8657,
                    'density' => null,
                    'latitude' => 35.3066988,
                    'longitude' => 74.7101998,
                    'map_zoom' => 10.5,
                ),
            139 =>
                array(
                    'id' => 134,
                    'province_id' => 6,
                    'division_id' => 33,
                    'name' => 'Diamer',
                    'center' => 'Chilas',
                    'population' => 131925,
                    'area' => 10936,
                    'density' => null,
                    'latitude' => 35.4985859,
                    'longitude' => 73.3684439,
                    'map_zoom' => 9,
                ),
            140 =>
                array(
                    'id' => 135,
                    'province_id' => 6,
                    'division_id' => 31,
                    'name' => 'Ghizer',
                    'center' => 'Gakuch',
                    'population' => 120218,
                    'area' => 9635,
                    'density' => null,
                    'latitude' => 36.3514589,
                    'longitude' => 72.8735893,
                    'map_zoom' => 9,
                ),
            141 =>
                array(
                    'id' => 136,
                    'province_id' => 6,
                    'division_id' => 31,
                    'name' => 'Gilgit',
                    'center' => 'Gilgit',
                    'population' => 243324,
                    'area' => 38000,
                    'density' => null,
                    'latitude' => 35.8630022,
                    'longitude' => 74.2414253,
                    'map_zoom' => 10,
                ),
            142 =>
                array(
                    'id' => 137,
                    'province_id' => 6,
                    'division_id' => 31,
                    'name' => 'Hunza',
                    'center' => 'Ali Abad',
                    'population' => 80355,
                    'area' => 17145,
                    'density' => null,
                    'latitude' => 36.544598,
                    'longitude' => 74.4935094,
                    'map_zoom' => 9,
                ),
            143 =>
                array(
                    'id' => 138,
                    'province_id' => 6,
                    'division_id' => 32,
                    'name' => 'Kharmang',
                    'center' => 'Madupur',
                    'population' => 20000,
                    'area' => null,
                    'density' => null,
                    'latitude' => 34.7883329,
                    'longitude' => 76.2492589,
                    'map_zoom' => 9,
                ),
            144 =>
                array(
                    'id' => 139,
                    'province_id' => 6,
                    'division_id' => 32,
                    'name' => 'Shigar',
                    'center' => 'Shigar',
                    'population' => 109000,
                    'area' => 8500,
                    'density' => null,
                    'latitude' => 35.4025039,
                    'longitude' => 75.4651401,
                    'map_zoom' => 10,
                ),
            145 =>
                array(
                    'id' => 140,
                    'province_id' => 6,
                    'division_id' => 31,
                    'name' => 'Nagar',
                    'center' => 'Nagar',
                    'population' => 89420,
                    'area' => 15567,
                    'density' => null,
                    'latitude' => 36.3039744,
                    'longitude' => 74.6405645,
                    'map_zoom' => 11,
                ),
            146 =>
                array(
                    'id' => 141,
                    'province_id' => 6,
                    'division_id' => 31,
                    'name' => 'Gupis–Yasin',
                    'center' => 'Ishkoman',
                    'population' => null,
                    'area' => null,
                    'density' => null,
                    'latitude' => 36.3055461,
                    'longitude' => 73.0612182,
                    'map_zoom' => 10,
                ),
            147 =>
                array(
                    'id' => 142,
                    'province_id' => 6,
                    'division_id' => 33,
                    'name' => 'Tangir',
                    'center' => 'Tangir',
                    'population' => null,
                    'area' => null,
                    'density' => null,
                    'latitude' => 35.6769294,
                    'longitude' => 73.2838036,
                    'map_zoom' => 11,
                ),
            148 =>
                array(
                    'id' => 143,
                    'province_id' => 6,
                    'division_id' => 33,
                    'name' => 'Darel',
                    'center' => 'Darel',
                    'population' => null,
                    'area' => null,
                    'density' => null,
                    'latitude' => 35.7337579,
                    'longitude' => 73.5463625,
                    'map_zoom' => 10,
                ),
            149 =>
                array(
                    'id' => 144,
                    'province_id' => 6,
                    'division_id' => 32,
                    'name' => 'Roundu',
                    'center' => 'Dambudas',
                    'population' => null,
                    'area' => null,
                    'density' => null,
                    'latitude' => 35.610569,
                    'longitude' => 74.8804371,
                    'map_zoom' => 10,
                ),

            151 =>
                array(
                    'id' => 145,
                    'province_id' => 7,
                    'division_id' => 35,
                    'name' => 'Muzaffarabad',
                    'center' => 'Muzaffarabad',
                    'population' => 650370,
                    'area' => 1642,
                    'density' => 394,
                    'latitude' => 34.3506667,
                    'longitude' => 73.4480674,
                    'map_zoom' => 12,
                ),
            152 =>
                array(
                    'id' => 146,
                    'province_id' => 7,
                    'division_id' => 35,
                    'name' => 'Hattian Bala',
                    'center' => 'Hattian Bala',
                    'population' => 230,529,
                    'area' => 854,
                    'density' => 270,
                    'latitude' => 34.1701289,
                    'longitude' => 73.7396936,
                    'map_zoom' => 15,
                ),
            153 =>
                array(
                    'id' => 147,
                    'province_id' => 7,
                    'division_id' => 35,
                    'name' => 'Neelum',
                    'center' => 'Athmuqam',
                    'population' => 191,251,
                    'area' => 3621,
                    'density' => 53,
                    'latitude' => 34.6045052,
                    'longitude' => 73.8440302,
                    'map_zoom' => 12,
                ),
            154 =>
                array(
                    'id' => 148,
                    'province_id' => 7,
                    'division_id' => 34,
                    'name' => 'Mirpur',
                    'center' => 'Mirpur',
                    'population' => 456,200,
                    'area' => 1010,
                    'density' => 452,
                    'latitude' => 33.2086178,
                    'longitude' => 73.4465242,
                    'map_zoom' => 10,
                ),
            155 =>
                array(
                    'id' => 149,
                    'province_id' => 7,
                    'division_id' => 34,
                    'name' => 'Bhimber',
                    'center' => 'Bhimber',
                    'population' => 420,624,
                    'area' => 1516,
                    'density' => 297,
                    'latitude' => 33.0095176,
                    'longitude' => 73.8622634,
                    'map_zoom' => 10,
                ),
            156 =>
                array(
                    'id' => 150,
                    'province_id' => 7,
                    'division_id' => 34,
                    'name' => 'Kotli',
                    'center' => 'Kotli',
                    'population' => 774194,
                    'area' => 1862,
                    'density' => 416,
                    'latitude' => 33.5057525,
                    'longitude' => 73.8014193,
                    'map_zoom' => 11,
                ),
            157 =>
                array(
                    'id' => 151,
                    'province_id' => 7,
                    'division_id' => 36,
                    'name' => 'Poonch',
                    'center' => 'Rawalakot',
                    'population' => 500571,
                    'area' => 855,
                    'density' => 585,
                    'latitude' => 33.786748,
                    'longitude' => 73.5258676,
                    'map_zoom' => 10,
                ),
            158 =>
                array(
                    'id' => 152,
                    'province_id' => 7,
                    'division_id' => 36,
                    'name' => 'Bagh',
                    'center' => 'Bagh',
                    'population' => 371919,
                    'area' => 770,
                    'density' => 483,
                    'latitude' => 34.0092762,
                    'longitude' => 73.5965401,
                    'map_zoom' => 10,
                ),
            159 =>
                array(
                    'id' => 153,
                    'province_id' => 7,
                    'division_id' => 36,
                    'name' => 'Haveli',
                    'center' => 'Forward Kahuta',
                    'population' => 152124,
                    'area' => 598,
                    'density' => 254,
                    'latitude' => 33.9258196,
                    'longitude' => 73.9637865,
                    'map_zoom' => 11,
                ),
            160 =>
                array(
                    'id' => 154,
                    'province_id' => 7,
                    'division_id' => 36,
                    'name' => 'Sudhnati',
                    'center' => 'Pallandari',
                    'population' => 297584,
                    'area' => 569,
                    'density' => 523,
                    'latitude' => 33.7063111,
                    'longitude' => 73.5954691,
                    'map_zoom' => 11,
                )
        ));

    }
}
